#ifndef __EW_DEMO_SECRETS_H


#define EW_DEMO_CLIENT_AP_SSID       "<SSID HERE>"
#define EW_DEMO_CLIENT_AP_PASSPHRASE "<IFI PASSWORD HERE>


#define THINGBOARD_DEVICE_TOKEN "<TOKEN HERE>"


#define __EW_DEMO_SECRETS_H
#endif /* __EW_DEMO_SECRETS_H */
